version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: order-registration-postgres
    environment:
      POSTGRES_DB: order_registration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - order-registration-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: order-registration-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - order-registration-network
    restart: unless-stopped

networks:
  order-registration-network:
    driver: bridge

volumes:
  postgres-data:
